name: Automatic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    name: Release
    uses: vm-x-ai/github-public-actions/.github/workflows/workflow-automatic-release.yml@main
    secrets: inherit
    with:
      publish: false

  dispatch:
    needs: [release]
    name: Dispatch release completed
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: release-completed
