name: Publish Production

on:
  workflow_dispatch:
    branches:
      - main

permissions:
  actions: write
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Publish Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: vm-x-ai/github-public-actions/.github/actions/setup-monorepo@main
        with:
          pnpm-version: 10
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_DEPLOYMENT_ROLE }}
          aws-region: ${{ vars.AWS_DEPLOYMENT_REGION }}
          role-session-name: GitHub
      - name: Publish
        run: pnpm nx affected -t publish
        env:
          VMX_PAT: ${{ secrets.VMX_PAT }}
          VMX_API_BASE_URL: ${{ vars.VMX_API_BASE_URL }}
